### PR TITLE
Updated README with Ubuntu 16.04 installation help

### PR DESCRIPTION
**Pull request by josephbales**

### CODE REVIEW

**Comment by maxbeizer** [comment]
@seanski any problem with this? The only thing I think could be problematic is hardcoding DB creds. What say you?

**Comment by josephbales** [comment]
I did another commit to remove the hardcoded DB creds.

**Comment by maxbeizer** [comment]
lgtm. @seanski ?

**Comment by seanski** [comment]
:shipit:

**Pull request merged**
